select * from EMP;

-- LA MEJOR PRAXIS ES UTILIZAR EL NOMBRE DE LOS CAMPOS
-- CONTROL + ENTER, EJECUTA LA LINEA EN LA QUE ESTAMOS POSICIONADOS

select APELLIDO, OFICIO, SALARIO from EMP;

-- ORDENACION DE DATOS, SIEMPRE AL FINAL Y AFECTA AL SELECT
-- LA ORDENACION SIEMPRE ES ASCENDENTE (asc)
select * from EMP ORDER BY APELLIDO

-- ORDENACION DESCENDIENTE DESC
select * from EMP ORDER BY APELLIDO DESC;

-- ORDENAR POR MAS DE UN CAMPO
select * from EMP order by DEPT_NO, OFICIO;

-- FILTRDO DE REGISTROS
-- OPERADORES DE COMPARACIÓN
/*
= igual
>= mayor o igual
< menor o igual
> mayor
< menor
<> distinto
*/
-- Oracle, por defecto, dierencia entre mayas y minus en sus textos 
--(string/vachar)

-- TODO LO QUE NO SEA UN NUMERO SE ESCRIBE ENTRE COMILLAS SIMPLES 

-- PARA FILTRAR SE UTILIZA LA PALABRA where Y SE ESCRIBE SOLAMENTE UNA VEZ EN 
-- TODA LA CONSULTA DESPUES DEL FROM QUE ESCRIBAMOS

-- MOSTRAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO 10
select * from EMP where DEPT_NO=10;

-- MOSTRAR TODOS LOS EMPLADOS CUYO OFICIO SEA DIRECTOR
select * from EMP where OFICIO='DIRECTOR';

-- MOSTRAR TODOS LOS EMPLEADOS CUYO OFICIO SEA DIFERENE A DIRECTOR
select * from EMP where OFICIO<>'DIRECTOR'

select * from EMP where OFICIO!='DIRECTOR'

-- OPERADORES RELACIONALES
-- NOS PERMITEN REALIZAR MAS DE UNA PREGUNTA DENTRO DE UNA CONSULTA
/*
OR --> MUESTRA LOS DATOS DE CADA FILTRO
AND --> TODOS LOS FILTROS DEBEN CUMPLIRSE
NOT --> NEGACION DE UNA CONDICION (EVITARLO SIEMPRE)
*/

--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 Y QUE TENGAN OFICIO DIRECTOR
select * from EMP where DEPT_NO=10 AND OFICIO='DIRECTOR';
select * from EMP where DEPT_NO=10 OR OFICIO='DIRECTOR' (EMPLEADOS DEL 10 QUE 
NO SEAN DIRECTORES y DIRECTORES QUE NO SEAN DEL 10)

--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 Y DEL 20
select * from EMP where DEPT_NO=10 OR DEPT_NO=20

--TENEMOS OTROS OPERADORES ADEMÁS DE LOS STANDARD
--BETWEEN MUESTRA LOS DATOS ENTRE UN RANGO INCLUSIVE
-- MOSTRAR LOS EMPLEADOS CUYO SALARIO ESTE ENTREN 251000 Y 390000
select * from EMP where SALARIO between 251000 and 390000 order by SALARIO

-- PODEMOS HACER LA MISMA CONSULTA CON OPERADORES Y ES EFICIENTE
select * from EMP where SALARIO >= 251000 and SALARIO <= 390000 order by SALARIO

-- LA NEGACION ES ALGO DE LO QUE DEBEMOS HUIR

-- MOSTRAR LOS EMPLEADOS QUE NO SEAN DIRECTOR
select * from EMP where NOT OFICIO='DIRECTOR' (hace dos consultas: una para 
todos los DIRECTOR y otra para todos los otros)

-- PODEMOS REALIZAR LA CONSULTA CON OPERADOR
select * from EMP where OFICIO<>'DIRECTOR' (acá solo se hace una consulta);

-- EXISTE UN OPERADOR PARA BUSCAR COINCIDENCIAS EN TEXTOS
-- NOS PERMITE, MEDIANTE CARACTERES ESPECIALES HACER FILTROS EN TEXTOS
/*
% busca cualquier caracter y longuitud
_ un caracter cualquier
? un caracter numérico
*/

-- MOSTRAR LOS EMPLEADOS CUYO APELLIDO COMIENZA EN s
select * from EMP where APELLIDO like 's%' (% busca cualquier caracter y 
longuitud);

-- MOSTRAR LOS EMPLEADOS CUYO APELLIDO COMIENZA EN s Y FINALIZA CON a
select * from EMP where APELLIDO like 's%a';

-- MOSTRAR TODOS LOS EMPLEADOS CUYO APELLIDO SEA DE 4 LETRAS
select * from EMP where APELLIDO like '____';

-- EXISTE OTRO OPERADOR PARA BUSCAR COINCIDENCIAS DE IGUALDAD EN UN MISMO CAMPO

-- CAMPO: in (valor1, valor2)

-- MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 Y DEL 20
select * from EMP where DEPT_NO = 10 or DEPT_NO = 20;

-- MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10, 20 Y 30
select * from EMP where DEPT_NO = 10 or DEPT_NO = 20 or DEPT_NO = 30;

-- MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10, 20, 30, 55, 65 Y 77
select * from EMP where DEPT_NO = 10 or DEPT_NO = 20 or DEPT_NO = 30 or 
DEPT_NO = 55 or DEPT_NO = 65 or DEPT_NO = 77
select * from EMP where DEPT_NO in (10, 20, 30, 55, 65, 77)

-- TENEMOS EL OPERADOR not in QUE REALIZA LO MISMO QUE in PERO RECUPERA 
--LOS QUE NO COINCIDEN
-- MOSTRAR TODOS LOS EMPLEADOS QUE NO ESTEN EN EL DEPARTAMENTO 10 Y 20
select * from EMP where not DEPT_NO in (10,20); -- NEGACION
select * from EMP where DEPT_NO not in (10,20); -- OPERADOR


-- CAMPO CALCULADOS
-- UN CAMPO CALCULADO ES UNA HERRAMIENTA EN UNA CONSULTA
-- SIEMPRE TIENE QUE TENER UN ALIAS
-- SIRVE PARA GENERAR CAMPOS QUE NO EXISTAN EN LA TABLA Y LOS PODEMOS CALCULAR
-- MOSTRAR EL APELLIDO, EL SALARIO, COMISION Y EL SALARIO TOTAL 
--(SALARIO + COMISION) DE TODOS LOS EMPLEADOS
-- UN CAMPO CALCULADO SOLO ES PARA EL CURSOR
select APELLIDO, SALARIO, COMISION, (SALARIO + COMISION) from EMP

select APELLIDO, SALARIO, COMISION, (SALARIO + COMISION) as TOTAL from EMP

-- MOSTRAR EL APELLIDO, EL SALARIO, COMISION Y EL SALARIO TOTAL 
--(SALARIO + COMISION) DE TODOS LOS EMPLEADOS
-- DE TODOS LOS EMPLEADOS CUYO SALARIO MAS COMISION ES MAYOR 344500
-- UN CAMPO CALCULADO SOLO ES PARA EL CURSOR (CURSO RESULTADO QUE SE MUESTRA)
select APELLIDO, SALARIO, COMISION, (SALARIO + COMISION) as TOTAL from EMP 
where (SALARIO + COMISION) >= 344500

-- QUEREMOS LA CONSULTA ORIGINAL Y ORDENAR POR ELLA
select APELLIDO, SALARIO, COMISION, (SALARIO + COMISION) as TOTAL from EMP 
order by TOTAL

-- order by ORDENA SOBRE LA TABLA Y EL CURSOR MIENTRAS QUE EL where SOLO SOBRE 
-- LA TABLA

--CLAUSULA DISTINT: SE UTILIZA PARA EL SELECT Y LO QUE REALIZA ES ELIMINAR 
-- REPETIDOS DE LA CONSULTA
--MOSTRAR EL OFICIO DE LOS EMPLEADOS
select OFICIO from EMP (todos);

--MOSTRAR LOS DIFERENTES OFICIOS DE LOS EMPLEADOS
select distinct OFICIO from EMP (sin duplicados);

--MOSTRAR LOS DIFERENTES OFICIOS, APELLIDOS DE LOS EMPLEADOS
select distinct OFICIO, APELLIDO from EMP (si hay dos PRESIDENTE con el mismo 
apellido solo aparecerá uno);

