-- SUBCONSULTAS

-- Son consultas que necesitan del resultao de otra consulta para poder ser 
--ejecutadas. No son autonomas, necesian de algo.

-- No importa el nivel de subconsulta, aunque pueden relantizar la respuesta

-- Generan bloqueos en consultas select, lo qe también relantiza las respuestas.

-- Debemos intentar evitarlas en la medida de lo posible con select

-- Ejemplos:

-- QUIERO VISUALIZAR LOS DATOS DEL EMPLEADO QUE MAS COBRA DE LA EMPRESA (EMP)

select max (SALARIO) from EMP;
- 650000

select * from EMP where SALARIO = 650000;

-- ENTONCES PODEMOS EJECUTAR AMBAS CONSULTAS A LA VEZ Y SE ANIDA EL RESULTADO DE
--DE UNA CONSULTA CON LA IGUALDAD DE LA RESPUESTA DE OTRA CONSULTA.
-- LAS SUBCONSULTAS VAN ENTRE PARENTESIS

select * from EMP where SALARIO =(select max (SALARIO) from EMP);


-- MOSTRAR LOS EMPLEADOS QUE TIENEN EL MISMO OFICIO QUE EL EMPLEADO gil Y QUE
--COBREN MENOS QUE jimenez

select * from EMP where OFICIO = 
(select OFICIO from EMP where APELLIDO = 'gil')
and SALARIO < (select SALARIO from EMP where APELLIDO='jimenez');


-- MOSTRAR LOS EMPLEADOS QUE TIENEN EL MISMO OFICIO QUE EL EMPLEADO gil Y EL
-- MISMO OFICIO QUE jimenez

-- SI UNA SUBCONSULA DEVUELVE MAS DE UN VALOR (DIRECTOR, ANALISTA), SE UTILIZA 
--EL OPERADOR IN

select * from EMP where OFICIO in 
(select OFICIO from EMP where APELLIDO = 'gil' or APELLIDO='jimenez')


-- POR SUPUESTO, PODEMOS UTILIZAR SUBCONSULTAS PARA OTRAS TABLAS

-- MOSTRAR EL APELLIDO Y EL OFICIO DE LOS EMPLEADOS DEL DEPARTAMENTO DE MADRID

select APELLIDO, OFICIO from EMP where DEPT_NO =
(select DEPT_NO from DEPT where LOC='MADRID')

-- ESTO DE ARRIBA ESTA MAL HECHO YA QUE LA TABLA EMP Y DEPT ESTAN RELACIONADAS,
--LAS SUBCONSULTAS SOLO ESTAN BIEN CUANDO LAS TABLAS NO SE RELACIONAN.

select EMP.APELLIDO, EMP.OFICIO
from EMP
inner join DEPT
on EMP.DEPT_NO=DEPT.DEPT_NO
where DEPT.LOC='MADRID'




-- CONSULTAS DE UNION

-- MUESTRAN, EN UN MISMO CURSOR, UN MISMO CONJUNTO DE RESULTADOS.

-- ESTAS COSNULTAS SE UTILIZAN COMO CONCEPTO, NO COMO RELACION.

-- DEBEMOS SERGUIR 3 NORMAS:

--1) LA PRIMERA CONSULTA ES LA JEFA

--2) TODAS LAS CONSULTAS DEBEN TENER EL MISMO NUMERO DE COLUMNAS

--3) TODAS LAS COLUMNAS DEBEN TENER EL MISMO TIPO DE DATO ENTRE SI

-- EN NUESTRA BBDD TENEMOS DATOS DE PERSONAS EN DIFERENTES TABLAS

--EMP, PLANTILLA Y DOCTOR

select APELLIDO, OFICIO, SALARIO from EMP;

select APELLIDO, FUNCION, SALARIO from PLANTILLA;

-- SI EJECUTAMOS LAS DOS AL MISMO TIEMPO HABRA DOS PESTAÑAS: UNA POR CADA CURSOR

select APELLIDO, OFICIO, SALARIO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA;

-- SI QUIERO NOMBRAR SALARIO as SUELDO SOLO SERVIRIA EN LA PRIMERA CONSULTA YA 
--QUE ES LA JEFA.

select APELLIDO, OFICIO, SALARIO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
union
select APELLIDO, ESPECIALIDAD, SALARIO from DOCTOR;

-- POR SUPUESTO PODEMOS ORDENAR SIN PROBLEMAS PERO ES RECOMNDABLE POR NUMERO DE
--COLUMNA.
-- SE PUEDE HACER POR NOMBRE DE COLUMNA PERO NOS QUITA LA POSIBILIDAD DE PONER
--ALIAS
-- SI TODAS LAS COLUMNAS SE LLAMAN IGUAL SE PUEDE FILTRAR CON NOMBRE, PERO SI SE 
--LLAMAN DIFERENTE (COLUMNA 2) NO SE PUEDE POR NOMBRE.

select APELLIDO, OFICIO, SALARIO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
union
select APELLIDO, ESPECIALIDAD, SALARIO from DOCTOR
order by 3;









-- PODEMOS PERFECTAMENTE FILRAR LOS DATOS DE LA CONSULTA.
-- POR EJEMPLO, MOSTRAR LOS DATOS DE LAS PERSONAS QUE COBREN MENOS DE 300000

select APELLIDO, OFICIO, SALARIO from EMP
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
union
select APELLIDO, ESPECIALIDAD, SALARIO from DOCTOR
where SALARIO < 300000
order by 1;

-- CADA FILTRO ES AFECTADO A CADA UNA DE LAS CONSULTAS.
-- EL WHERE DE ARRIBA SOLO VA A FILTRAR LA CONSULTA DE ARRIBA, NO DE TODA LAS
--QUE ESTAN EN UNION. SI QUIERO FILTRAR POR TODOS EL WHERE TIENE QUE IR EN CADA
--CONSULTA INDIVIDUAL:

select APELLIDO, OFICIO, SALARIO from EMP
where SALARIO < 300000
union
select APELLIDO, FUNCION, SALARIO from PLANTILLA
where SALARIO < 300000
union
select APELLIDO, ESPECIALIDAD, SALARIO from DOCTOR
where SALARIO < 300000
order by 1;

-- UNION ELIMINA LOS RESULTADOS REPETIDOS Y POR ESTO AUNQUE LA CONSULTA SEA LA
--MISMA SOLO NOS APARECERÁ UNOS RESULTADOS

select APELLIDO, OFICIO from EMP
union
select APELLIDO, OFICIO from EMP;

-- PERO SI QUEREMOS REPETIR HAY QUE USAR UNION ALL

select APELLIDO, OFICIO from EMP
union all
select APELLIDO, OFICIO from EMP;





